### ISSUE TITLE
Deluge doesn't recognise symlinked NAS folder for "Downloads"

### ISSUE THREAD

**Issue by Rhfelwr** [GreenFrogSB/LMDS#17]
I created the following symlinks:

```
pi@raspberrypi:~/LMDS/media $ sudo ln -s /mnt/BFDS/tvshows /home/pi/LMDS/media/tvshows
pi@raspberrypi:~/LMDS/media $ sudo ln -s /mnt/BFDS/movies /home/pi/LMDS/media/movies
pi@raspberrypi:~/LMDS $ sudo ln -s /mnt/BFDS/downloads /home/pi/LMDS/downloads
```

Then I ran ./deploy.sh, then deployed the containers with docker-compose up -d. When I enter the Deluge WebUI through Portainer it says "Error" in the bottom right corner for free space. If I go into Preferences/Downloads and change the "Download to" field from /root/Downloads to just /Downloads it sees the free space and my NAS share. 

When inspecting the configuration in Portainer I see the following default setup:

```
Host/volume                                          Path in container
/home/pi/LMDS/downloads                    /downloads
/home/pi/LMDS/volumes/deluge/config  /config

```
So what is wrong here? is there some problem with the symlink I created? My NAS is mounted properly with fstab set up and all that. Also alongside this issue I also see that Sonarr and Radarr reports an error, that "Deluge is downloading to /root folder which is unsafe", what is the deal with that?

Please help, and thanks a lot in advance! :)

**Comment by GreenFrogSB** [comment]
The error you saw at the beginning regarding your downloads storage
capacity is to be expected. This is coming from container default config
that I am not able to correct as I am not a developer of deluge container.
The workaround you already implemented is all to be done just change
download settings in deluge Web UI from /root/Downloads to just /Downloads.

Rebot all the containers after above is done. Then warning about
downloading to root should be also gone.

All is due to this small, tiny misconfiguration of default downloads
locations in deluge that I am not able to change myself.

I hope that helps.

**Comment by Rhfelwr** [comment]
Thanks! It makes sense, I spoke with the linuxserver.io guys on Discord and they said the same. Do the alternative torrent clients like QBittorrent/Transmission etc. suffer from the same issue or is it only Deluge?

**Comment by GreenFrogSB** [comment]
I think Deluge is the only one with this out of the box config issue. Nevertheless, I continue using it as my primary download client. There are other plugin in Deluge that work for me and this small thing at the beginning is a small price to pay for other perx there.
