### ISSUE TITLE
Support of rclone to use it with gsuit library

### ISSUE THREAD

**Issue by 420tushar** [GreenFrogSB/LMDS#18]
Your script is awsome made my work like done in just a matter seconds the only thing i am missing and unable to make it work with is rclone.
I tried doing rclone mount 
And change mount point through portainer but when i use rclone mount dir in mount point it throws error tried googling everything nothing worked 😐.  [  error while creating mount source path '/home/kratos/media': mkdir /home/kratos/media: file exists ]
I would love to get it within your script

**Comment by GreenFrogSB** [comment]
I am not entirely sure, but just by reading the message rclone complains that it is unable to create a folder "/home/kratos/media" maybe rename existing folder, if you have anything there and then try mount again the same way? I suspect if media folder wont exist in /home/kratos/ it might work. Let us know. This is going to be more rclone specific question rather than LMDS bug of malfunction.
